name: 'customer_churn_dbt'
version: '1.0.0'
config-version: 2

profile: 'customer_churn_profile'

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  customer_churn_dbt:
    +materialized: view
